<!-- Header -->
<?php include("header.php") ?>
<!-- End Header -->

<div class="main-wrp">
   
    <div class="top-navtext">
        <div class="container">
            <ul>
                <li>
                    <a href="#"><i class="fas fa-home"></i></a>
                </li>
                <li><a href="#">Products</a></li>
                <li>Closet</li>
                <li>One Piece Closet</li>
            </ul>
        </div>
    </div>

    <section class="product-overview">
        <div class="container">
            <div class="title-bx">
                <h1>One Piece Closet</h1>
            </div>
            <div class="row">
               <div class="col-md-4 col-sm-4 col-lg-3">
                    <div class="overview-left">
                        <div class="inner-title">
                            <h4><i class="fas fa-filter"></i> FILTER</h4>
                        </div>
                        <div id="accordion">
                            <div class="card">
                                <div class="card-header" data-toggle="collapse" href="#collapseOne">Wash basins</div>
                                <div id="collapseOne" class="collapse" data-parent="#accordion">
                                    <div class="card-body">
                                        <a href="wash-basins.php">Table Top Basins <span>(08)</span> </a>
                                        <a href="half-pedestal.php">Half pedestal Wash basins <span>(22)</span></a>
                                        <a href="wash-basic-pedastal.php">Wash basic pedastal <span>(26)</span> </a>
                                        <a href="counter-basin.php">Counter basin <span>(44)</span> </a>
                                    </div>
                                </div>
                            </div>

                            <div class="card">
                                <div class="card-header" data-toggle="collapse" href="#Color">Faucet For Kitchen</div>
                                <div id="Color" class="collapse" data-parent="#accordion">
                                    <div class="card-body">
                                        <a href="kitchen-taps.php">Kitchen Taps <span>(08)</span> </a>
                                        <a href="kitchen-sinks.php">Kitchen Sinks <span>(22)</span></a>
                                        <a href="#">Kitchen Accessoires <span>(26)</span> </a>
                                    </div>
                                </div>
                            </div>

                            <div class="card">
                                <div class="card-header" data-toggle="collapse" href="#Accessories">Attico Accessories</div>
                                <div id="Accessories" class="collapse" data-parent="#accordion">
                                    <div class="card-body">
                                        <a href="Accessories.php">Accessories <span>(75/113)</span> </a>
                                        <a href="#">Seat Cover <span>(75/113)</span> </a>
                                        <a href="#">Faucet <span>(78)</span></a>
                                    </div>
                                </div>
                            </div>

                            <div class="card">
                                <div class="card-header" data-toggle="collapse" href="#Closet">Closet</div>
                                <div id="Closet" class="collapse" data-parent="#accordion">
                                    <div class="card-body">
                                        <a href="wall-hang-closet.php">Wall hang closet <span>(46)</span> </a>
                                        <a href="water-closet.php">Water closet <span>(50)</span> </a>
                                        <a href="one-pice-closet.php">One Piece closet <span>(60)</span> </a>
                                    </div>
                                </div>
                            </div>

                            <div class="card">
                                <div class="card-header" data-toggle="collapse" href="#Bathroom">Bathroom Accessories</div>
                                <div id="Bathroom" class="collapse" data-parent="#accordion">
                                    <div class="card-body">
                                        <a href="cistern.php">Concealed Cistern</a>
                                        <a href="flush-plate.php">Concealed Tank Flush Plate </a>
                                        <a href="3dflus.php">3D Flush Tank</a>
                                        <a href="color-flush.php">Dual Color Flush Tank</a>
                                        <a href="seat-cover-Installation.php ">Seat Cover Installation Instruction</a>
                                        <a href="piece-fitting.php">One Piece Fitting</a>
                                        <a href="didet.php">Didet</a>
                                        <a href="baccessories.php">Accessories</a>
                                        <a href="pan.php"> Pan</a>
                                        <a href="urinal.php"> Urinal</a>
                                        <a href="bath-tub.php"> Bath Tub</a>
                                    </div>
                                </div>
                            </div>

                            <div class="card">
                                <div class="card-header" data-toggle="collapse" href="#Faucet">Faucet</div>
                                <div id="Faucet" class="collapse" data-parent="#accordion">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-6 col-sm-6">
                                                <a href="gla.php">Gla</a>
                                                <a href="lucia.php">Lucia </a>
                                                <a href="spogo.php">Spago</a>
                                                <a href="sfera.php">Sfera</a>
                                                <a href="fijian.php">Fijian</a>
                                                <a href="ptrsian.php">Persian</a>
                                                <a href="alora.php">Alora</a>
                                                <a href="agnese.php">Agnese</a>
                                            </div>
                                            <div class="col-md-6 col-sm-6">
                                                <a href="aida.php">Aida</a>
                                                <a href="alberto.php">Alberto</a>
                                                <a href="aldo.php">Aldo</a>
                                                <a href="alex.php">Alex</a>
                                                <a href="alfonso.php">Alfonso</a>
                                                <a href="amedeo.php">Amedeo</a>
                                                <a href="aldrea.php">Aldrea</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="card">
                                <div class="card-header" data-toggle="collapse" href="#Showers">Showers</div>
                                <div id="Showers" class="collapse" data-parent="#accordion">
                                    <div class="card-body">
                                        <a href="shower.php">Showers</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-8 col-sm-4 col-lg-9">
                    <div class="overview-right">
                        <div class="top-rightbar">
                            <div class="row">
                                <div class="col-md-6 col-sm-6">
                                    <h2><strong>15</strong> PRODUCTS</h2>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <!--  <div class="Sort-by">
                                    <ul>
                                        <li>
                                            <div class="form-group">
                                                <label for="exampleFormControlSelect1">Sort by</label>
                                                <select class="form-control" id="exampleFormControlSelect1">
                                                    <option>1</option>
                                                    <option>2</option>
                                                    <option>3</option>
                                                    <option>4</option>
                                                    <option>5</option>
                                                </select>
                                            </div>
                                        </li>
                                        <li>
                                            <a href="#">20</a>
                                            <a href="#">|</a>
                                            <a href="#">40</a>
                                            <p>Results/Page</p>
                                        </li>
                                    </ul>
                                </div> -->
                                </div>
                            </div>
                        </div>

                        <div class="overview-block">
                            <div class="row">
                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/1.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SETTARA OPC 101</h2>
                                                <p>L 690 W 355 H 770mm<span>S-trap Distance 255mm (9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹13760</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/2.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SHAMAY OPC 102</h2>
                                                <p>L 700 W 400 H 690mm<span>S-trap Distance 255mm (9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹13720</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/3.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SHARNTA OPC 103</h2>
                                                <p>L 650 W 365 H 665mm<span>S-trap Distance 300mm (12")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹14890</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/4.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SIBYLA OPC 104</h2>
                                                <p>L 650 W 330 H 690mm<span>S-trap Distance 255mm (9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹12980</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/5.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SIDONIE OPC 105</h2>
                                                <p>L 660 W 335 H 700mm<span>S-trap Distance 255mm (9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹13300</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/6.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SILANA OPC 106</h2>
                                                <p>L 680 W 360 H 710mm<span>S-trap Distance 100/255mm (94"/9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹14390</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/7.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SIMONE OPC 107</h2>
                                                <p>L 670 W 345 H 715mm<span>S-trap Distance 100/255/300mm (4"9"/12"/)</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹13420</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/8.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SLANIA OPC 108</h2>
                                                <p>L 655 W 350 H 710mm<span>S-trap Distance 100/255mm (4"/9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹13880</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/9.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SIDONIE OPC 109</h2>
                                                <p>L 675 W 350 H 750mm<span>S-trap Distance 255mm (9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹15010</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/10.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SOLEIL OPC 110</h2>
                                                <p>L 690 W 340 H 710mm<span>S-trap Distance 255mm (9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹14170</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/11.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>STEFANIA OPC 111</h2>
                                                <p>L 650 W 350 H 740mm<span>S-trap Distance 100/255mm (4"/9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹16720</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/12.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SUSANNE OPC 112</h2>
                                                <p>L 650 W 350 H 730mm<span>S-trap Distance 255mm (9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹13530</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/13.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>OLIVIA OPC 114</h2>
                                                <p>L 675 W 365 H 710mm<span>S-trap Distance 100/255mm (4"/9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹15420</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/14.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>SYDNYE OPC 113</h2>
                                                <p>L 770 W 390 H 680mm<span>S-trap Distance 255mm (9")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹13880</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-4 col-lg-4">
                                    <div class="overview-img">
                                        <img src="images/closet/one-pice-closet/15.jpg" alt="Avatar" class="image" />
                                        <div class="overlay">
                                            <div class="text">
                                                <h2>AVA OPC 115</h2>
                                                <p>L 660 W 350 H 740mm<span>S-trap Distance 300mm (12")</span></p>
                                                <p><strong>Color</strong> : White, Ivory</p>
                                                <!-- <p><strong>Price</strong> : ₹15420</p> -->
                                                <a href="#" type="button" data-toggle="modal" data-target="#quote-modal" >Get a quote</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- Footer -->
<?php include("footer.php") ?>
<!-- End Footer -->
